version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run:
        name: 'Installing dependencies'
        command: 'npm install'
      - run:
        name: 'Running tests'
        command: 'node ace test'
workflows:
  version: 2
  test:
    jobs:
      - test
