version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run:
          name: 'Installing dependencies'
          command: 'npm install'
      - run:
          name: 'Running tests'
          command: 'ENV_PATH=.env.testing node ace test unit'
workflows:
  version: 2
  test:
    jobs:
      - test
